Dism /online /Disable-Feature /FeatureName:AppServerClient `
 /FeatureName:Printing-PrintToPDFServices-Features         `
 /FeatureName:Windows-Defender-Default-Definitions         `
 /FeatureName:Printing-XPSServices-Features                `
 /FeatureName:SearchEngine-Client-Package                  `
 /FeatureName:MSRDC-Infrastructure                         `
 /FeatureName:TelnetClient                                 `
 /FeatureName:TFTP                                         `
 /FeatureName:TIFFIFilter                                  `
 /FeatureName:WorkFolders-Client                           `
 /FeatureName:LegacyComponents                             `
 /FeatureName:DirectPlay                                   `
 /FeatureName:Printing-Foundation-Features                 `
 /FeatureName:Printing-Foundation-InternetPrinting-Client  `
 /FeatureName:Printing-Foundation-LPDPrintService          `
 /FeatureName:Printing-Foundation-LPRPortMonitor           `
 /FeatureName:SimpleTCP                                    `
 /FeatureName:MicrosoftWindowsPowerShellV2Root             `
 /FeatureName:MicrosoftWindowsPowerShellV2                 `
 /FeatureName:Windows-Identity-Foundation                  `
 /FeatureName:Client-ProjFS                                `
 /FeatureName:Client-DeviceLockdown                        `
 /FeatureName:Client-EmbeddedShellLauncher                 `
 /FeatureName:Client-EmbeddedBootExp                       `
 /FeatureName:Client-EmbeddedLogon                         `
 /FeatureName:Client-KeyboardFilter                        `
 /FeatureName:Client-UnifiedWriteFilter                    `
 /FeatureName:DataCenterBridging                           `
 /FeatureName:NetFx3                                       `
 /FeatureName:IIS-WebServerRole                            `
 /FeatureName:IIS-WebServer                                `
 /FeatureName:IIS-CommonHttpFeatures                       `
 /FeatureName:IIS-HttpErrors                               `
 /FeatureName:IIS-HttpRedirect                             `
 /FeatureName:IIS-ApplicationDevelopment                   `
 /FeatureName:IIS-Security                                 `
 /FeatureName:IIS-RequestFiltering                         `
 /FeatureName:IIS-NetFxExtensibility                       `
 /FeatureName:IIS-NetFxExtensibility45                     `
 /FeatureName:IIS-HealthAndDiagnostics                     `
 /FeatureName:IIS-HttpLogging                              `
 /FeatureName:IIS-LoggingLibraries                         `
 /FeatureName:IIS-RequestMonitor                           `
 /FeatureName:IIS-HttpTracing                              `
 /FeatureName:IIS-URLAuthorization                         `
 /FeatureName:IIS-IPSecurity                               `
 /FeatureName:IIS-Performance                              `
 /FeatureName:IIS-HttpCompressionDynamic                   `
 /FeatureName:IIS-WebServerManagementTools                 `
 /FeatureName:IIS-ManagementScriptingTools                 `
 /FeatureName:IIS-IIS6ManagementCompatibility              `
 /FeatureName:IIS-Metabase                                 `
 /FeatureName:WAS-WindowsActivationService                 `
 /FeatureName:WAS-ProcessModel                             `
 /FeatureName:WAS-NetFxEnvironment                         `
 /FeatureName:WAS-ConfigurationAPI                         `
 /FeatureName:IIS-HostableWebCore                          `
 /FeatureName:IIS-StaticContent                            `
 /FeatureName:IIS-DefaultDocument                          `
 /FeatureName:IIS-DirectoryBrowsing                        `
 /FeatureName:IIS-WebDAV                                   `
 /FeatureName:IIS-WebSockets                               `
 /FeatureName:IIS-ApplicationInit                          `
 /FeatureName:IIS-ASPNET                                   `
 /FeatureName:IIS-ASPNET45                                 `
 /FeatureName:IIS-ASP                                      `
 /FeatureName:IIS-CGI                                      `
 /FeatureName:IIS-ISAPIExtensions                          `
 /FeatureName:IIS-ISAPIFilter                              `
 /FeatureName:IIS-ServerSideIncludes                       `
 /FeatureName:IIS-CustomLogging                            `
 /FeatureName:IIS-BasicAuthentication                      `
 /FeatureName:IIS-HttpCompressionStatic                    `
 /FeatureName:IIS-ManagementConsole                        `
 /FeatureName:IIS-ManagementService                        `
 /FeatureName:IIS-WMICompatibility                         `
 /FeatureName:IIS-LegacyScripts                            `
 /FeatureName:IIS-LegacySnapIn                             `
 /FeatureName:IIS-FTPServer                                `
 /FeatureName:IIS-FTPSvc                                   `
 /FeatureName:IIS-FTPExtensibility                         `
 /FeatureName:WCF-Services45                               `
 /FeatureName:WCF-HTTP-Activation45                        `
 /FeatureName:WCF-TCP-Activation45                         `
 /FeatureName:WCF-Pipe-Activation45                        `
 /FeatureName:WCF-MSMQ-Activation45                        `
 /FeatureName:WCF-TCP-PortSharing45                        `
 /FeatureName:MSMQ-Container                               `
 /FeatureName:MSMQ-DCOMProxy                               `
 /FeatureName:MSMQ-Server                                  `
 /FeatureName:MSMQ-ADIntegration                           `
 /FeatureName:MSMQ-HTTP                                    `
 /FeatureName:MSMQ-Multicast                               `
 /FeatureName:MSMQ-Triggers                                `
 /FeatureName:IIS-CertProvider                             `
 /FeatureName:IIS-WindowsAuthentication                    `
 /FeatureName:IIS-DigestAuthentication                     `
 /FeatureName:IIS-ClientCertificateMappingAuthentication   `
 /FeatureName:IIS-IISCertificateMappingAuthentication      `
 /FeatureName:IIS-ODBCLogging                              `
 /FeatureName:WCF-HTTP-Activation                          `
 /FeatureName:WCF-NonHTTP-Activation                       `
 /FeatureName:NetFx4-AdvSrvs                               `
 /FeatureName:NetFx4Extended-ASPNET45                      `
 /FeatureName:ServicesForNFS-ClientOnly                    `
 /FeatureName:ClientForNFS-Infrastructure                  `
 /FeatureName:NFS-Administration                           `
 /FeatureName:SMB1Protocol                                 `
 /FeatureName:SMB1Protocol-Client                          `
 /FeatureName:SMB1Protocol-Server                          `
 /FeatureName:SMB1Protocol-Deprecation                     `
 /FeatureName:SmbDirect                                    `
 /FeatureName:HostGuardian                                 `
 /FeatureName:MultiPoint-Connector                         `
 /FeatureName:MultiPoint-Connector-Services                `
 /FeatureName:MultiPoint-Tools                             `
 /FeatureName:MediaPlayback                                `
 /FeatureName:Microsoft-Windows-Subsystem-Linux            `
 /FeatureName:HypervisorPlatform                           `
 /FeatureName:VirtualMachinePlatform                       `
 /FeatureName:Containers-DisposableClientVM                `
 /FeatureName:Microsoft-Hyper-V-All                        `
 /FeatureName:Microsoft-Hyper-V                            `
 /FeatureName:Microsoft-Hyper-V-Tools-All                  `
 /FeatureName:Microsoft-Hyper-V-Management-PowerShell      `
 /FeatureName:Microsoft-Hyper-V-Hypervisor                 `
 /FeatureName:Microsoft-Hyper-V-Services                   `
 /FeatureName:Microsoft-Hyper-V-Management-Clients         `
 /FeatureName:DirectoryServices-ADAM-Client                `
 /FeatureName:Windows-Defender-ApplicationGuard            `
 /FeatureName:Containers